# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- ci

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  displayName: Setup
  inputs:
    versionSource: 'spec'
    versionSpec: '6.x'
    checkLatest: true
- script: 'npm install'
  displayName: "Instala dependências"
  
- script: "npm run reporterjunit"
  displayName: "Executa os Testes"
- task: PublishTestResults@2
  displayName: "Gera o Relatório"
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'